group1_serenading: True
group1:
  - name: "Esteban"
    rank: ["X","N7","A7"]
    nmax: 1
  - name: "Antoine"
    rank: ["N7","X","A7"]
    nmax: 1
  - name: "Yvan"
    rank: ["N7","X","A7"]
    nmax: 1

group2:
  - name: "N7"
    rank: ["Esteban", "Yvan", "Antoine"]
    nmax: 1
  - name: "X"
    rank: ["Antoine", "Esteban", "Yvan"]
    nmax: 1
  - name: "A7"
    rank: ["Yvan", "Esteban", "Antoine"]
    nmax: 1
