students_serenading: True
students:
  - "Esteban" : ["X","N7","A7"]
  - "Antoine" : ["N7","X","A7"]
  - "Yvan" : ["N7","X","A7"]
schools:
  - "N7" : ["Esteban", "Yvan", "Antoine"]
  - "X" : ["Antoine", "Esteban", "Yvan"]
  - "A7" : ["Yvan", "Esteban", "Antoine"]
